name: Compilar Mod Direto
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Baixar SDK Necessario
        run: |
          git clone --depth 1 https://github.com sdk
          echo "PS4SDK=$GITHUB_WORKSPACE/sdk" >> $GITHUB_ENV

      - name: Instalar Compilador
        run: sudo apt-get update && sudo apt-get install -y clang lld llvm make

      - name: Compilar
        run: make
        env:
          CC: clang
          CXX: clang++

      - name: Baixar Mod Pronto
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Assalto_CUSA03140
          path: "*.sprx"
